---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: [duckduckgo, google]
    target: _blank
    focus: true

- datetime:
    text_size: xl
    format:
      timeStyle: short

