# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#lovelace:
#  mode: yaml


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
template: !include template.yaml
alert: !include alerts.yaml

plant:
  pianta_balcone:
    sensors:
      moisture: sensor.plant_sensor_cda4_moisture
      battery: sensor.plant_sensor_cda4_battery
      temperature: sensor.plant_sensor_cda4_temperature
      conductivity: sensor.plant_sensor_cda4_conductivity
      brightness: sensor.plant_sensor_cda4_illuminance

      
mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  include:
    entity_globs:
      - sensor.view_plus*

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"


homeassistant:
  packages: !include_dir_named packages

smartir:

media_player:
  - platform: smartir
    name: Barra soggiorno
    unique_id: living_room_audiobar
    device_code: 1125
    controller_data: zigbee2mqtt/RemoteControlSoggiorno/set/ir_code_to_send


climate:
  - platform: smartir
    name: Condizionatore soggiorno
    unique_id: condizionatore_soggiorno
    device_code: 5001
    controller_data: zigbee2mqtt/RemoteControlSoggiorno/set/ir_code_to_send
    temperature_sensor: sensor.view_plus_temperature
    humidity_sensor: sensor.view_plus_humidity