#- platform: viaggiatreno
#  train_id: 2454
#  station_id: S05043
#  train_name: treno Lambrate 7.29

#- platform: viaggiatreno
#  train_id: 2156
#  station_id: S02336
#  train_name: treno Lambrate 7.34

#- platform: viaggiatreno
#  train_id: 10856
#  station_id: S05000
#  train_name: treno Lambrate 7.40

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'


