- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

- platform: template
  sensors:
    nightstate:
      friendly_name: Night State
      value_template: "{% if is_state('sun.sun', 'below_horizon') %}1{% else %}0{% endif %}"

- platform: viaggiatreno
  train_id: 2454
  station_id: S05043
  train_name: treno Lambrate 7.29

- platform: viaggiatreno
  train_id: 2156
  station_id: S02336
  train_name: treno Lambrate 7.34

- platform: viaggiatreno
  train_id: 10856
  station_id: S05000
  train_name: treno Lambrate 7.40
